### ISSUE TITLE
GitHub Basics Course steps to de completed

### ISSUE THREAD

**Issue by Kaeanel** [Kaeanel/treehouse_github_basics#2]
## TODO
*Steps left to complete the Treehouse GitHub Basics Course*

* [x] Hello, Github!
* [x] Working by yourself
* [ ] Working on a Team
* [ ] Create a web presence on GitHub
* [ ] Get Involved in Open Source

🎉👌 

cc @Kaeanel
